# Generated by Django 4.2.7 on 2025-12-04 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("QUESTIONS", "Questions du Forum"),
                            ("MENTORS", "Recherche de Mentors"),
                            ("OPPORTUNITIES", "Opportunités"),
                            ("TOOLS", "Outils Pédagogiques"),
                            ("USERS", "Utilisateurs"),
                            ("GENERAL", "Recherche Générale"),
                        ],
                        max_length=20,
                    ),
                ),
                ("search_query", models.CharField(max_length=500)),
                ("search_count", models.IntegerField(default=0)),
                ("last_searched", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Recherche Populaire",
                "verbose_name_plural": "Recherches Populaires",
                "db_table": "popular_searches",
                "ordering": ["-search_count", "-last_searched"],
                "unique_together": {("category", "search_query")},
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("QUESTIONS", "Questions du Forum"),
                            ("MENTORS", "Recherche de Mentors"),
                            ("OPPORTUNITIES", "Opportunités"),
                            ("TOOLS", "Outils Pédagogiques"),
                            ("USERS", "Utilisateurs"),
                            ("GENERAL", "Recherche Générale"),
                        ],
                        db_index=True,
                        help_text="Type de contenu recherché",
                        max_length=20,
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        db_index=True,
                        help_text="Texte saisi par l'utilisateur",
                        max_length=500,
                    ),
                ),
                (
                    "filters_applied",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Filtres appliqués lors de la recherche (ex: {"status": "solved", "tags": ["math"]})',
                    ),
                ),
                (
                    "results_count",
                    models.IntegerField(
                        default=0, help_text="Nombre de résultats retournés"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID de session pour regrouper les recherches d'une même visite",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Adresse IP de l'utilisateur", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent du navigateur"),
                ),
                (
                    "page_url",
                    models.CharField(
                        blank=True,
                        help_text="URL de la page où la recherche a été effectuée",
                        max_length=500,
                    ),
                ),
                (
                    "clicked_result_id",
                    models.CharField(
                        blank=True,
                        help_text="ID du résultat cliqué (si applicable)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "clicked_result_position",
                    models.IntegerField(
                        blank=True,
                        help_text="Position du résultat cliqué dans la liste",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur qui a effectué la recherche (null si anonyme)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recherche",
                "verbose_name_plural": "Recherches",
                "db_table": "search_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-created_at"],
                        name="search_logs_categor_24bab5_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="search_logs_user_id_30eff5_idx",
                    ),
                    models.Index(
                        fields=["search_query"], name="search_logs_search__18b7a2_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="search_logs_created_9a6547_idx"
                    ),
                ],
            },
        ),
    ]
