# Generated by Django 4.2.7 on 2025-11-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "Système"),
                            ("REPLY", "Réponse"),
                            ("MENTORSHIP", "Mentorat"),
                            ("ACHIEVEMENT", "Succès"),
                            ("MESSAGE", "Message"),
                            ("BOOKING", "Réservation"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "db_table": "notification_titles",
            },
        ),
        migrations.CreateModel(
            name="NotificationReadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_history",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "db_table": "notification_read_history",
            },
        ),
        migrations.CreateModel(
            name="NotificationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("message", models.TextField()),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "db_table": "notification_messages",
            },
        ),
    ]
