# Generated by Django 4.2.7 on 2025-12-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Ex: Étudiants formés', max_length=100)),
                ('value', models.CharField(help_text='Ex: 5000+', max_length=50)),
                ('icon', models.CharField(help_text="Nom de l'icône Lucide (ex: Users, GraduationCap)", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description courte')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Statistique d'impact",
                'verbose_name_plural': "Statistiques d'impact",
                'db_table': 'impact_stats',
                'ordering': ['order'],
            },
        ),
    ]
