# Generated by Django 4.2.7 on 2025-12-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_id', models.CharField(help_text='Identifiant unique (ex: calc, chem)', max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Nom de l'icône Lucide", max_length=50)),
                ('category', models.CharField(choices=[('Sciences', 'Sciences'), ('Créativité', 'Créativité'), ('Langues', 'Langues'), ('Informatique', 'Informatique')], max_length=50)),
                ('level', models.CharField(choices=[('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Lycée', 'Lycée'), ('Tous niveaux', 'Tous niveaux')], max_length=50)),
                ('color', models.CharField(help_text="Classes Tailwind pour le fond de l'icône (ex: bg-blue-100)", max_length=100)),
                ('text_color', models.CharField(help_text="Classes Tailwind pour la couleur de l'icône (ex: text-blue-600)", max_length=100)),
                ('bg_gradient', models.CharField(help_text='Classes Tailwind pour le dégradé (ex: from-blue-500 to-cyan-400)', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('dev', 'En développement')], default='available', max_length=20)),
                ('link', models.CharField(blank=True, help_text='Lien interne (ex: /tools/calculator) ou externe', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Outil d'apprentissage",
                'verbose_name_plural': "Outils d'apprentissage",
                'db_table': 'learning_tools',
                'ordering': ['order'],
            },
        ),
    ]
