# Generated by Django 4.2.7 on 2025-12-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learningtool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Ex: Étudiante en Chimie', max_length=100)),
                ('country', models.CharField(help_text='Ex: Sénégal', max_length=100)),
                ('text', models.TextField(help_text='Le témoignage')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'db_table': 'testimonials',
                'ordering': ['order'],
            },
        ),
    ]
