# Generated by Django 4.2.7 on 2025-12-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter (X)'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('email', 'Email'), ('website', 'Site Web'), ('other', 'Autre')], max_length=50)),
                ('name', models.CharField(help_text='Nom affiché (ex: LinkedIn)', max_length=100)),
                ('url', models.URLField(help_text='Lien complet (ex: https://linkedin.com/in/...)')),
                ('icon', models.CharField(help_text="Nom de l'icône Lucide (ex: Linkedin, Twitter, Mail)", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lien social',
                'verbose_name_plural': 'Liens sociaux',
                'db_table': 'social_links',
                'ordering': ['order'],
            },
        ),
    ]
