# Generated by Django 4.2.7 on 2025-12-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_is_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_keys',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
