# Generated by Django 4.2.7 on 2025-12-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_encrypted_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_visible_to_recipient',
            field=models.BooleanField(default=False, help_text='Visible seulement pendant un rendez-vous'),
        ),
    ]
