# Generated by Django 4.2.7 on 2025-11-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AITutorQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("model_used", models.CharField(max_length=50)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_tutor_questions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AITutorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.CharField(blank=True, max_length=50, null=True)),
                ("total_questions", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Session Tuteur IA",
                "verbose_name_plural": "Sessions Tuteur IA",
                "db_table": "ai_tutor_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=50)),
                ("code", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Snippet de Code",
                "verbose_name_plural": "Snippets de Code",
                "db_table": "code_snippets",
                "ordering": ["-created_at"],
            },
        ),
    ]
