# Generated by Django 4.2.7 on 2025-11-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "db_table": "badges",
            },
        ),
        migrations.CreateModel(
            name="BadgeColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("color", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "badge_colors",
            },
        ),
        migrations.CreateModel(
            name="BadgeCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("POINTS_THRESHOLD", "Seuil de points"),
                            ("FIRST_ACTION", "Première action"),
                            ("ACTION_COUNT", "Nombre d'actions"),
                            ("STREAK", "Série consécutive"),
                        ],
                        max_length=50,
                    ),
                ),
                ("criteria_value", models.JSONField()),
            ],
            options={
                "verbose_name": "Critère Badge",
                "verbose_name_plural": "Critères Badges",
                "db_table": "badge_criteria",
            },
        ),
        migrations.CreateModel(
            name="BadgeDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "badge_descriptions",
            },
        ),
        migrations.CreateModel(
            name="BadgeIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("icon", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "badge_icons",
            },
        ),
        migrations.CreateModel(
            name="BadgeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "badge_names",
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("awarded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Badge Utilisateur",
                "verbose_name_plural": "Badges Utilisateurs",
                "db_table": "user_badges",
                "ordering": ["-awarded_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPointsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("points_change", models.IntegerField()),
                ("previous_total", models.IntegerField()),
                ("new_total", models.IntegerField()),
                ("reason", models.CharField(db_index=True, max_length=255)),
                (
                    "related_content_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Historique Points",
                "verbose_name_plural": "Historiques Points",
                "db_table": "user_points_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
