# Generated by Django 4.2.7 on 2025-11-29 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpointshistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gamification.badge"
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_badges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="badgename",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="names",
                to="gamification.badge",
            ),
        ),
        migrations.AddField(
            model_name="badgeicon",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="icons",
                to="gamification.badge",
            ),
        ),
        migrations.AddField(
            model_name="badgedescription",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descriptions",
                to="gamification.badge",
            ),
        ),
        migrations.AddField(
            model_name="badgecriteria",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="gamification.badge",
            ),
        ),
        migrations.AddField(
            model_name="badgecolor",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colors",
                to="gamification.badge",
            ),
        ),
        migrations.AddIndex(
            model_name="userpointshistory",
            index=models.Index(
                fields=["user", "-created_at"], name="user_points_user_id_8e6e03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpointshistory",
            index=models.Index(fields=["reason"], name="user_points_reason_7998a8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge", "is_active")},
        ),
    ]
