# Generated by Django 4.2.7 on 2025-11-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SCHOLARSHIP", "Bourse"),
                            ("CONTEST", "Concours"),
                            ("INTERNSHIP", "Stage"),
                            ("TRAINING", "Formation"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(db_index=True)),
                ("external_link", models.URLField(max_length=500)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("views_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Opportunité",
                "verbose_name_plural": "Opportunités",
                "db_table": "opportunities",
                "ordering": ["-is_featured", "deadline"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "opportunity_descriptions",
            },
        ),
        migrations.CreateModel(
            name="OpportunityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("image_url", models.URLField(max_length=500)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "opportunity_images",
            },
        ),
        migrations.CreateModel(
            name="OpportunityLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("location", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "opportunity_locations",
            },
        ),
        migrations.CreateModel(
            name="OpportunityProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("provider", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "opportunity_providers",
            },
        ),
        migrations.CreateModel(
            name="OpportunityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("tag", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "db_table": "opportunity_tags",
            },
        ),
        migrations.CreateModel(
            name="OpportunityTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "opportunity_titles",
            },
        ),
        migrations.CreateModel(
            name="OpportunityView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "db_table": "opportunity_views",
            },
        ),
    ]
