# Generated by Django 4.2.7 on 2025-11-29 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opportunitytitle",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="titles",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunitytag",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunityprovider",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="providers",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunitylocation",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunityimage",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunitydescription",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descriptions",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["type", "deadline", "is_active"],
                name="opportuniti_type_c51f5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["-is_featured", "-created_at"],
                name="opportuniti_is_feat_77a0d8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="opportunitytag",
            unique_together={("opportunity", "tag", "is_active")},
        ),
    ]
