# Generated by Django 4.2.7 on 2025-12-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunityimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='opportunityimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunities/images/'),
        ),
    ]
