# Generated by Django 4.2.7 on 2025-11-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Lundi"),
                            ("TUESDAY", "Mardi"),
                            ("WEDNESDAY", "Mercredi"),
                            ("THURSDAY", "Jeudi"),
                            ("FRIDAY", "Vendredi"),
                            ("SATURDAY", "Samedi"),
                            ("SUNDAY", "Dimanche"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "db_table": "mentor_availabilities",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="MentorBio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("bio", models.TextField()),
            ],
            options={
                "db_table": "mentor_bios",
            },
        ),
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("rating", models.FloatField(db_index=True, default=0.0)),
                ("reviews_count", models.IntegerField(db_index=True, default=0)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("total_sessions", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Profil Mentor",
                "verbose_name_plural": "Profils Mentors",
                "db_table": "mentor_profiles",
            },
        ),
        migrations.CreateModel(
            name="MentorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review",
                        to="bookings.booking",
                    ),
                ),
                (
                    "mentor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="mentors.mentorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "mentor_reviews",
            },
        ),
        migrations.CreateModel(
            name="MentorSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("specialty", models.CharField(db_index=True, max_length=100)),
                (
                    "mentor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialties",
                        to="mentors.mentorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "mentor_specialties",
            },
        ),
        migrations.CreateModel(
            name="MentorSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("LINKEDIN", "LinkedIn"),
                            ("TWITTER", "Twitter"),
                            ("WEBSITE", "Site Web"),
                            ("GITHUB", "GitHub"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "mentor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="mentors.mentorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "mentor_socials",
            },
        ),
        migrations.CreateModel(
            name="MentorReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("comment", models.TextField()),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="mentors.mentorreview",
                    ),
                ),
            ],
            options={
                "db_table": "mentor_review_comments",
            },
        ),
    ]
