# Generated by Django 4.2.7 on 2025-11-29 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mentors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorreview",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mentorbio",
            name="mentor_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bios",
                to="mentors.mentorprofile",
            ),
        ),
        migrations.AddField(
            model_name="mentoravailability",
            name="mentor_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="mentors.mentorprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mentorspecialty",
            unique_together={("mentor_profile", "specialty", "is_active")},
        ),
        migrations.AlterUniqueTogether(
            name="mentorsocial",
            unique_together={("mentor_profile", "platform", "is_active")},
        ),
        migrations.AlterUniqueTogether(
            name="mentorreview",
            unique_together={("mentor_profile", "student", "booking", "is_active")},
        ),
        migrations.AddIndex(
            model_name="mentorprofile",
            index=models.Index(
                fields=["rating", "is_verified", "is_active"],
                name="mentor_prof_rating_d84600_idx",
            ),
        ),
    ]
