# Generated by Django 4.2.7 on 2025-11-30 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cv_file', models.FileField(upload_to='mentors/cvs/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('bio', models.TextField()),
                ('university', models.CharField(blank=True, max_length=255)),
                ('specialties', models.JSONField(default=list)),
                ('availability', models.JSONField(default=dict)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
                ('twitter', models.URLField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
