# Generated by Django 4.2.7 on 2025-12-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mentors", "0003_mentorapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorSpecificDateAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("specific_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "mentor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_date_availabilities",
                        to="mentors.mentorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "mentor_specific_date_availabilities",
                "ordering": ["specific_date", "start_time"],
                "unique_together": {
                    ("mentor_profile", "specific_date", "start_time", "is_active")
                },
            },
        ),
    ]
