# Generated by Django 4.2.7 on 2025-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentorspecificdateavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='ai_recommendation',
            field=models.TextField(blank=True, verbose_name='Recommandation IA'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score de confiance IA'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='ai_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', "En cours d'analyse"), ('COMPLETED', 'Analyse terminée'), ('FAILED', "Échec de l'analyse")], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='ai_validated',
            field=models.BooleanField(default=False, verbose_name="Validé par l'IA"),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='id_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/ids/'),
        ),
    ]
